server:
    applicationConnectors:
        - type: http
          port: 8080
          bindHost: localhost
        - type: https
          port: 8443
          keyStorePath: example.keystore
          keyStorePassword: example
          validateCerts: false
logging:
    loggers:
          org.hibernate.SQL: ALL
    appenders:
        - type: console
          threshold: DEBUG
          target: stdout
        - type: file
          currentLogFilename: logs/dropwizardtest.log
          archivedLogFilenamePattern: logs/dropwizardtest-%d.log.gz
          archivedFileCount: 5
          threshold: ALL
          timeZone: UTC
database:
    driverClass: oracle.jdbc.OracleDriver
    user: DB_USER
    password: DB_PASS
    url: DB_URL
    properties:
        hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    validationQuery: "SELECT 1 FROM dual"
    initialSize: 2
    minSize: 1
    maxSize: 5